name: Test run
on: [push]
jobs:
  dm1:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Translate dm1
        run: |
          wget -O https://github.com/teeworlds/teeworlds/raw/0.6/data/maps/dm1.map
          ./twmap_6to7.py dm1.map dm1_07.map -Wall -Werror

